language: python
cache: pip
sudo: required
python:
  - 3.6

env:
  global:
  - TERRAFORM_VERSION=0.11.10

jobs:
  include:
    - stage: "Lint/Format/Validate/Test"
      env: NEEDS_PYTHON_REQS="yes";NEEDS_TERRAFORM="yes"
      name: "Lint/Format/Validate"
      script: ./scripts/travis_lint_format_validate.sh
    - script: nosetests
      name: "Unit Tests"
    - stage: "Deploy"
      env: NEEDS_TERRAFORM="yes"
      after_success: skip
      script: ./deployment/scripts/deploy.sh

install:
  - |
    if [ "${NEEDS_TERRAFORM}" = "yes" ]; then
      curl -fSL "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip" -o terraform.zip;
      sudo unzip terraform.zip -d /opt/terraform;
      sudo ln -s /opt/terraform/terraform /usr/bin/terraform;
      rm -f terraform.zip;
    fi

  - |
    if [ "${NEEDS_PYTHON_REQS}" = "yes" ]; then
      pip install -r requirements-test.txt;
    fi

after_success:
  - codecov