language: python
cache: pip
sudo: required
python:
  - 3.6

env:
  global:
    - TERRAFORM_VERSION=0.11.10

#stages:
#  - name: deploy
#    if: branch = master

before_install:
  # https://github.com/travis-ci/travis-ci/issues/7940#issuecomment-311411559
  - export BOTO_CONFIG=/dev/null

install:
  # Install terraform
  - curl -fSL "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip

  # Install reqs for testing
  - pip install -r requirements-test.txt

script:
  - pushd terraform
  - terraform init
  - terraform validate
  - terraform fmt -check=true -diff=true
  - popd

  - nosetests -v --with-coverage --cover-tests --cover-package=lambda_function.isa_tab_exporter,tests

  - black --check --diff .
  - flake8

after_success:
  - codecov

#deploy:
#  provider: script
#  script: bash deploy.sh