language: python
cache: pip
python:
  - 3.6

env:
  global:
    - TERRAFORM_VERSION=0.11.7

#stages:
#  - name: deploy
#    if: branch = master

before_install:
  # https://github.com/travis-ci/travis-ci/issues/7940#issuecomment-311411559
  - export BOTO_CONFIG=/dev/null

install:
  # Install terraform
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/$TERRAFORM_VERSION/terraform_$TERRAFORM_VERSION_linux_amd64.zip
  - unzip /tmp/terraform.zip -d /tmp
  - mv /tmp/terraform ~/bin
  - export PATH="~/bin:$PATH"

  # Install reqs for testing
  - pip install -r requirements_test.txt


script:
  - pushd terraform
  - terraform init
  - terraform validate
  - terraform fmt -check=true -diff=true
  - popd

  - nosetests --with-coverage --cover-tests

after_success:
  - codecov

#deploy:
#  provider: script
#  script: bash deploy.sh