language: python
cache: pip
sudo: required
python:
  - 3.6

stages:
  - name: deploy
    if: branch = master

env:
  global:
  - TERRAFORM_VERSION=0.11.10
  - AWS_DEFAULT_REGION=us-east-1
  # AWS_ACCESS_KEY_ID
  - secure: "J8YhSUyvl7bnyqJQ/9xkwDSYqcWNxkPrsxBXaIHtyjh2hHZ0jm74aAWiGEHXeFXMOjbk+Yu6SB5l6wsjcfU7NvCNRmtKFA5iBX0/Se8+vjBNlE8uvPOhQSfRMPq3QoHm3tRvtEFeE5fJWNK9R6ElEpI3lPd/NJqXRhITZDCERmvrPtBJFjURuIyDiPVj5VxkwPWgXn0X61tsP0bQmM1V9Y2nrPj+QjN77M0A6aPl2QYmFKrtpPXqKezmPUZKrpKkY07GER4/P/aZJjyAheBmTYFIsTLvrcsoaROcsxfKATjIm7edM+X7Lwz9MuWtjumguQtnqRFQOwY3GWuv5MQeUb1Z96EVZ+Dj/LXXj9zEO7nZiXUX+AUG7wWjA8Gou1mnFcdr76LFrHnhtxeSdCIwlh3iavfjCxgZytGLHbTmYZP5hIbB74zje98NeC/EJgOX9gtSC7zZwKFKhShAhEZCCZHnjDZYCJDa9Fk3zcjtVy04ElRGWzJh04O5N/JBlzD6h1KyBNcg33iFIW5hvMc0u7JligGiiP5SIvejfK53c8mSN6RwL9vioCQ6yNi0Z/zFv+M23zBltdtCP4nCmqWLkjOPlS9EK5IZGH0nkzEEhDtPsnJUVWWFjF2YivPjcQ1X2UN4XLAWjUhgayxwfX49pGum6YeU1mfgq8RwbY3X2Ps="
  # AWS_SECRET_ACCESS_KEY
  - secure: "osGpEGjAdAb/gGDQ/MP6RzuZJtDF3ktFYxWxZE2KY7YIdBeDEzfI62tbkf+3Ir6OkbVvnzAZkzTU81kW05n8AQCyC91DPr8PvDc6ceu8jhn+xh4qKacmsYqzORdobiKKoWa8vahjddzHvCve/+4DehZybqzPkFN2dCj+CPQqznZmvxD5ZFCqCPEDzoHkb3nzZhdqR3/N9mVxtXBpqUMoKAWP+wQWuFqEgOy2dgYieKPYeCuHYGhX//EJVR8aWWzeqtqr6OeNoBwjRXRhpvC744mYammPGmHbBjq30WrkrB4ZxL8c9trJiBk/8M17oipdLnZ5kKoX8TbVXon4oIbOnPYBBa3lAUO+HN5hf+d3iV+D/NTcf2L1gcuY+kjBdwRs7RyN/qm3tsOSpZE9WfU9dJwlmAMTqzWjSqnrrdMxLCkz13EdMuM3vKMdKzX/MQRlhb2umTX33MJOfaECvkSG2KOuvLEvIfgMmEc23P51qjkGgUVccpBZMUVE7j46TaTlVIxlK9ANMPcn/pH9Lj9ARav9EOOpYBeqdrSu3+i05I1+e3ih84GoEwm7fkSxtykLJzC9e2YdnU8Z+aDpU2efkb5qaDYKKYJ/+cQ+3R+txDSBxDKKl3Qf85BCS2VFxHS+vDiEpkvl/7UDzv0ex4sat07f7qt3zHFsEinjxGQZr7k="
  # ACM_CERTIFICATE_ARN
  - secure: "oLyr2mrOxyIjTbpaeazxF0G6s0KPVxfGTZT/O2OreKNT2BvY9RdGYdTzdWPl7Dztes6B4SynsF7oQGrE2wK8maw+UiSaYkZpbcbpPv6E0rSa9o4KiZ+qTSwdHLGoLTM8myaiSeKtGOip5zID0niwViY1qWvcaspOibu1g+f2EeZg+btbJL7NbtUDj3zvsHHNubSUzPvj2fAm8qwoeNaaogm7voWUxJbJK8prdNECsLH1xRgXxnBifPGWVpySGZrIENRu5A7OScAx1hanTlTz8y2Jc7kx9vCojii9RbkAZ5ICpvSAqVmHZyHaCJMfRc2D4jI9eozJKY0BgbNGWkDYiqrq7clgrXSVYbbcKW3d9U4EymkdeheMhNDS4c/v5IrIf7GuVWj422Wkj1xzPTkUo7PI39oJWbuvAxsdbpZl5SV3Ok48NscjoRtvchT6t/LsvxtqBFtZORYppIhgH4/rCkuR8tniWPBvZSjXyx8utCgURqfZaR4fe6logeCOB8njmOCGtTSQWtq7JTT3SrYIELP/1m78XYoqcSxAKFgidcZKgB5OYSTRVt6OBvpY9LBn4a3BkIt2ZjUhzf3Uc97QLBahtlhm0fCWuJ/LT4Z9nTvxFxMpvhB8ZNIJCMU6qOCzUbYjm/ykIzcxNZzUQ4dCVWOVCFIJuraM0qbMF3UXOcM="
  # ROUTE_53_HOSTED_ZONE_ID
  - secure: "ThCSxPEiB39VRfGpQyW5zrDGfCaK3gsleNeq/HKqmsibayuVmU7puUK/CJNlcbeVYJnjRDJeFLaoF6G49vMvoDJkhNErQ5EfalNNrNtfMYNv4yTVtyovpLczTgP1e/2Cq+4BBjnOb5KsBN2ix+wYEfl7pURfEIrSeV93yO1NaXdHg4BIVYQa6I8Or87PxcYp0zXwcvyJsBOpDA3PqaG2UQ9ziSeKVdw6O6OCE5gDK5QH44H9rf9u/1fxaBs3Ty6sW9QtqAfdarEST0DJyUMFA00ByHalnj5c4ThYIC3aCEYXkUqrrFD2H8ICDVSV/4liFn8fOKYkpk9nVs2simHVTexyYTUq9lvmKdExZQYsm+OTYL8AsHRGO2t+IFzd7Eu2aeFjuMj1nAWvqxg2I0MArTbZexsQPH54jpGhGT8Iqesqw4I6AHP8J3W1uTFozYohJ+65ksjz5Z/Q4GGphs0SluIuQolG+o/7KozozhPnEHPlJA6tw4dVTgaMLpF6TOZKfruHYxfeB90oafcD9edaBM3RXAYU6aEojjT1L3pRS3YtScfZpvueMv/8JwG3kUhHGaasoPe+GybthwZI6zUYDsxOB5txuanQfmIqQsCdT9xtP/jDl4bZ85rnbxINrSEO4w/+v3roAW0a2yDuyMg4NfZaaUnInG1OW0MnLbmXDYo="

before_install:
  # https://github.com/travis-ci/travis-ci/issues/7940#issuecomment-311411559
  - export BOTO_CONFIG=/dev/null

install:
  # Install terraform
  - curl -fSL "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip

  # Install reqs for testing
  - pip install -r requirements-test.txt

script:
  - black --check --diff .
  - flake8

  - nosetests

  - pushd terraform
  - terraform init
  - terraform validate
  - terraform fmt -check=true -diff=true
  - terraform plan -detailed-exitcode
  - popd

after_success:
  - codecov

deploy:
  provider: script
  script: bash deploy.sh