language: python
cache: pip
sudo: required
python:
  - 3.6

stages:
  - name: deploy
    if: branch = master

env:
  global:
  - TERRAFORM_VERSION=0.11.10

install:
  # Install terraform
  - curl -fSL "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip

  # Install reqs for testing
  - pip install -r requirements-test.txt

script:
  - black --check --diff .
  - flake8

  - nosetests

  - pushd terraform
  - terraform init -input=false
  - terraform validate
  - terraform fmt -check=true -diff=true
  - popd

after_success:
  - codecov

deploy:
  provider: script
  script: bash deploy.sh